'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.1
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property Tarneeb() As Byte
        Get
            Return CType(Me("Tarneeb"),Byte)
        End Get
        Set
            Me("Tarneeb") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property CurrentBet() As Byte
        Get
            Return CType(Me("CurrentBet"),Byte)
        End Get
        Set
            Me("CurrentBet") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property HumanTeamScore() As Integer
        Get
            Return CType(Me("HumanTeamScore"),Integer)
        End Get
        Set
            Me("HumanTeamScore") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property ComputerTeamScore() As Integer
        Get
            Return CType(Me("ComputerTeamScore"),Integer)
        End Get
        Set
            Me("ComputerTeamScore") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("255")>  _
    Public Property BetOwner() As Byte
        Get
            Return CType(Me("BetOwner"),Byte)
        End Get
        Set
            Me("BetOwner") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property TurnNum() As Byte
        Get
            Return CType(Me("TurnNum"),Byte)
        End Get
        Set
            Me("TurnNum") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property GameLevel() As Byte
        Get
            Return CType(Me("GameLevel"),Byte)
        End Get
        Set
            Me("GameLevel") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property BackCardDesign() As Byte
        Get
            Return CType(Me("BackCardDesign"),Byte)
        End Get
        Set
            Me("BackCardDesign") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("red")>  _
    Public Property BackCardColor() As String
        Get
            Return CType(Me("BackCardColor"),String)
        End Get
        Set
            Me("BackCardColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property HumanPlayValue() As Byte
        Get
            Return CType(Me("HumanPlayValue"),Byte)
        End Get
        Set
            Me("HumanPlayValue") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property HumanPlayFamily() As Byte
        Get
            Return CType(Me("HumanPlayFamily"),Byte)
        End Get
        Set
            Me("HumanPlayFamily") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property PlayersTurn() As String
        Get
            Return CType(Me("PlayersTurn"),String)
        End Get
        Set
            Me("PlayersTurn") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property UseCustomBackSide() As Boolean
        Get
            Return CType(Me("UseCustomBackSide"),Boolean)
        End Get
        Set
            Me("UseCustomBackSide") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property CustomBackSideFileName() As String
        Get
            Return CType(Me("CustomBackSideFileName"),String)
        End Get
        Set
            Me("CustomBackSideFileName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("00:00:00")>  _
    Public Property TotalGameTime() As Global.System.TimeSpan
        Get
            Return CType(Me("TotalGameTime"),Global.System.TimeSpan)
        End Get
        Set
            Me("TotalGameTime") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property TotalWonGames() As Integer
        Get
            Return CType(Me("TotalWonGames"),Integer)
        End Get
        Set
            Me("TotalWonGames") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property TotalLostGames() As Integer
        Get
            Return CType(Me("TotalLostGames"),Integer)
        End Get
        Set
            Me("TotalLostGames") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property TotalGamesPlayed() As Integer
        Get
            Return CType(Me("TotalGamesPlayed"),Integer)
        End Get
        Set
            Me("TotalGamesPlayed") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property ResetDate() As Date
        Get
            Return CType(Me("ResetDate"),Date)
        End Get
        Set
            Me("ResetDate") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("00:00:00")>  _
    Public Property PeriodGameTime() As Global.System.TimeSpan
        Get
            Return CType(Me("PeriodGameTime"),Global.System.TimeSpan)
        End Get
        Set
            Me("PeriodGameTime") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property PeriodWonGames() As Integer
        Get
            Return CType(Me("PeriodWonGames"),Integer)
        End Get
        Set
            Me("PeriodWonGames") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property PeriodLostGames() As Integer
        Get
            Return CType(Me("PeriodLostGames"),Integer)
        End Get
        Set
            Me("PeriodLostGames") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property PeriodGamesPlayed() As Integer
        Get
            Return CType(Me("PeriodGamesPlayed"),Integer)
        End Get
        Set
            Me("PeriodGamesPlayed") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property TurnFamily() As Byte
        Get
            Return CType(Me("TurnFamily"),Byte)
        End Get
        Set
            Me("TurnFamily") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property FamiliesByDescending() As Boolean
        Get
            Return CType(Me("FamiliesByDescending"),Boolean)
        End Get
        Set
            Me("FamiliesByDescending") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property CardsByDescending() As Boolean
        Get
            Return CType(Me("CardsByDescending"),Boolean)
        End Get
        Set
            Me("CardsByDescending") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("120")>  _
    Public Property AngleBetweenFirstAndLastCard() As Byte
        Get
            Return CType(Me("AngleBetweenFirstAndLastCard"),Byte)
        End Get
        Set
            Me("AngleBetweenFirstAndLastCard") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property GameComment() As String
        Get
            Return CType(Me("GameComment"),String)
        End Get
        Set
            Me("GameComment") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property GameCommentTimeout() As Integer
        Get
            Return CType(Me("GameCommentTimeout"),Integer)
        End Get
        Set
            Me("GameCommentTimeout") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property PreparationPlayersOrder() As String
        Get
            Return CType(Me("PreparationPlayersOrder"),String)
        End Get
        Set
            Me("PreparationPlayersOrder") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("English")>  _
    Public Property Language() As String
        Get
            Return CType(Me("Language"),String)
        End Get
        Set
            Me("Language") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
    Public Property AngleBetweenEachCard() As Decimal
        Get
            Return CType(Me("AngleBetweenEachCard"),Decimal)
        End Get
        Set
            Me("AngleBetweenEachCard") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.MyTarneeb.MySettings
            Get
                Return Global.MyTarneeb.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
